trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
    pwd
    ls -al
  displayName: 'npm install and build'

- task: CopyPublishBuildArtifacts@1  
  displayName: 'Copy Publish Artifact: angular-web-app'  
  inputs:  
    CopyRoot: dist  
    Contents: '**'  
    ArtifactName: $(Build.Repository.Name) 
    ArtifactType: Container
